### POST Request (Create User)
POST http://localhost:8080/auth/createUser
Accept: application/json
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "qwerty1234*"
}
###

### GET Request (Get User)
GET http://localhost:8080/auth/getUser?uid=uFMguV1L5LWjecJ8oA1xSye6b742

###
